#!/bin/bash
set -x

mkdir -p /var/vcap/sys/log

NFS_STORE='/var/vcap/store'
EXPORTS='/export'
FILE_STORE='filestore'
SHARED_HOME='artifactory_shared_home'
ARTIFACTORY_SHARED_HOME="$NFS_STORE/$SHARED_HOME"
EXPORT_SHARED_HOME="$EXPORTS/$SHARED_HOME"
ARTIFACTORY_ETC="$ARTIFACTORY_SHARED_HOME/ha-etc"
ARTIFACTORY_DATA="$ARTIFACTORY_SHARED_HOME/ha-data"
ARTIFACTORY_FILE_STORE="$ARTIFACTORY_DATA/$FILE_STORE"
ARTIFACTORY_BACKUP="$ARTIFACTORY_SHARED_HOME/ha-backup"

exec > >(tee -a >(logger -p user.info -t vcap.$(basename $0).stdout) | awk -W interactive '{lineWithDate="echo [`date +\"%Y-%m-%d %H:%M:%S%z\"`] \"" $0 "\""; system(lineWithDate)  }' >>/var/vcap/sys/log/$(basename $0).log)
exec 2> >(tee -a >(logger -p user.error -t vcap.$(basename $0).stderr) | awk -W interactive '{lineWithDate="echo [`date +\"%Y-%m-%d %H:%M:%S%z\"`] \"" $0 "\""; system(lineWithDate)  }' >>/var/vcap/sys/log/$(basename $0).err.log)

case $1 in

  start)
    dpkg --unpack -E /var/vcap/packages/debian_nfs_server/nfs-kernel-server_1.2.0-4ubuntu4.2_amd64.deb
    rm -rf /etc/init.d/nfs-kernel-server
    #BLOCK:  Make Mount points
    #TODO: Fix the permissions model on this

    #shared (CLUSTER_HOME) directory
    mkdir -p $ARTIFACTORY_SHARED_HOME
    chown vcap:vcap $ARTIFACTORY_SHARED_HOME
    chmod ugo+rw $ARTIFACTORY_SHARED_HOME
    #make the subdirectories.  Making them here so they can be more easily shared later
    mkdir -p $ARTIFACTORY_ETC
    chown vcap:vcap $ARTIFACTORY_ETC
    chmod ugo+rw $ARTIFACTORY_ETC

    mkdir -p $ARTIFACTORY_DATA
    chown vcap:vcap $ARTIFACTORY_DATA
    chmod ugo+rw $ARTIFACTORY_DATA

    mkdir -p $ARTIFACTORY_BACKUP
    chown vcap:vcap $ARTIFACTORY_BACKUP
    chmod ugo+rw $ARTIFACTORY_BACKUP
    #ENDBLOCK: Make Mount Points
    #Make the bind directories
    mkdir -p $EXPORTS
    chown vcap:vcap $EXPORTS
    chmod ugo+rw $EXPORTS

    mkdir -p $EXPORT_SHARED_HOME
    chown vcap:vcap $EXPORT_SHARED_HOME
    chmod ugo+rw $EXPORT_SHARED_HOME
    #End making of Bind Directories
    #eliminates all mount points from fstab using /var/vcap/store and appends the config fstab
    sed -i '\#^/var/vcap/store/# d;r /var/vcap/jobs/debian_nfs_server/config/fstab' /etc/fstab

    cp -f /var/vcap/jobs/debian_nfs_server/config/exports /etc/exports

    modprobe -q nfsd

    for f in /var/lib/nfs/etab  \
      /var/lib/nfs/rmtab \
      /var/lib/nfs/xtab; do
      [ -e $f ] || touch $f
    done

    if ! mountpoint -q /proc/fs/nfsd; then
      mount -t nfsd nfsd /proc/fs/nfsd
    fi

    mount -a
    
    /usr/sbin/exportfs -r
    /usr/sbin/rpc.nfsd 8

    cp -f /var/vcap/jobs/debian_nfs_server/config/idmapd.conf /etc/idmapd.conf
#    /etc/init.d/idmapd restart
#TODO:  Fix the idmapd restart
    pidof nfsd | cut -f 1 -d \ > /var/vcap/sys/run/rpc_nfsd.pid
    echo 'end start'
    ;;

  stop)
    kill -2 $(pidof nfsd)

    /usr/sbin/exportfs -au
    if mountpoint -q /proc/fs/nfsd; then
      /usr/sbin/exportfs -f
    fi

   if grep -qsE "artifactory_shared_home" /proc/mounts; then
       umount /export/artifactory_shared_home -lf
   fi
   if mountpoint -q /proc/fs/nfsd; then
      umount /proc/fs/nfsd -lf
   fi
   sleep 5
 #  modprobe -r nfsd
   echo 'end stop'
    ;;

  *)
    echo "Usage: rpc_nfsd_ctl {start|stop}"

    ;;

esac
