#!/bin/bash
set -x

mkdir -p /var/vcap/sys/log

exec > >(tee -a >(logger -p user.info -t vcap.$(basename $0).stdout) | awk -W interactive '{lineWithDate="echo [`date +\"%Y-%m-%d %H:%M:%S%z\"`] \"" $0 "\""; system(lineWithDate)  }' >>/var/vcap/sys/log/$(basename $0).log)
exec 2> >(tee -a >(logger -p user.error -t vcap.$(basename $0).stderr) | awk -W interactive '{lineWithDate="echo [`date +\"%Y-%m-%d %H:%M:%S%z\"`] \"" $0 "\""; system(lineWithDate)  }' >>/var/vcap/sys/log/$(basename $0).err.log)

case $1 in

  start)
    dpkg --unpack -E /var/vcap/packages/debian_nfs_server/nfs-kernel-server_1.2.0-4ubuntu4.2_amd64.deb
    rm -rf /etc/init.d/nfs-kernel-server
    mkdir -p /var/vcap/store/artifactory_file_store
    chown vcap:vcap /var/vcap/store/artifactory_file_store
    chmod ugo+rw /var/vcap/store/artifactory_file_store

    cp -f /var/vcap/jobs/debian_nfs_server/config/exports /etc/exports

    modprobe -q nfsd

    for f in /var/lib/nfs/etab  \
      /var/lib/nfs/rmtab \
      /var/lib/nfs/xtab; do
      [ -e $f ] || touch $f
    done

    if ! mountpoint -q /proc/fs/nfsd; then
      mount -t nfsd nfsd /proc/fs/nfsd
    fi

    /usr/sbin/exportfs -r
    /usr/sbin/rpc.nfsd 8

    cp -f /var/vcap/jobs/debian_nfs_server/config/idmapd.conf /etc/idmapd.conf
    /etc/init.d/idmapd restart

    pidof nfsd | cut -f 1 -d \ > /var/vcap/sys/run/rpc_nfsd.pid

    ;;

  stop)
    kill -2 $(pidof nfsd)

    /usr/sbin/exportfs -au
    if mountpoint -q /proc/fs/nfsd; then
      /usr/sbin/exportfs -f
    fi

    ;;

  *)
    echo "Usage: rpc_nfsd_ctl {start|stop}"

    ;;

esac
