#!/bin/bash
# vim: set ft=sh

set -e -x

VERSION=$(cat ./version/number)
if [ -z "$VERSION" ]; then
  echo "missing version number"
  exit 20
fi

cd artifactory-bosh-release-master

bosh target ${BOSH_TARGET}
bosh -n create release --with-tarball --version $VERSION
bosh -n upload release
bosh -n --deployment ${BOSH_MANIFEST} deploy
