#!/bin/bash
# vim: set ft=sh

set -e -x

VERSION=$(cat ./version/number)
if [ -z "$VERSION" ]; then
  echo "missing version number"
  exit 20
fi

if [ -z "$ARTIFACTORY_LICENSE" ]; then
  echo "missing artifactory license"
  exit 30
fi

cd artifactory-bosh-release-master

bosh -n target ${BOSH_TARGET}
bosh -n login ${BOSH_USERNAME} ${BOSH_PASSWORD}
bosh -n create release --version $VERSION
bosh -n upload release
bosh -n --deployment ${BOSH_MANIFEST} deploy
