#!/bin/bash
# vim: set ft=sh

set -e -x

cd artifactory-bosh-release-master

echo $PATH

export PATH=/home/vcap/.rbenv/bin:/home/vcap/.rbenv/shims:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

echo $PATH

bundle --version

bundle config build.nokogiri --use-system-libraries

bundle install

bundle exec rspec --format d
