#!/bin/bash
# vim: set ft=sh

set -e

export BOSH_USER=admin
export BOSH_PASSWORD=admin

bosh target ${BOSH_LITE_IP}

# create and upload concourse release
pushd artifactory-bosh-release/
  bosh -n upload release  
popd

#run ruby test
