#!/bin/bash
# vim: set ft=sh

set -e -x

cd artifactory-bosh-release-master

bundle --version

bundle config build.nokogiri --use-system-libraries

bundle install --path vendor/bundle

bundle exec rspec --format d
