#!/bin/bash
# vim: set ft=sh

set -e -x

git clone --recursive ./artifactory-bosh-release-master ./final-bosh

VERSION=$(cat ./version/version)
if [ -z "$VERSION" ]; then
  echo "missing version number"
  exit 20
fi

cp jfrog-artf-bosh-concourse-credentials/bosh/private.yml final-bosh/config/private.yml

cd final-bosh

git config --global user.email "ci@localhost"
git config --global user.name "CI Bot"

bosh -n create release --final --with-tarball --version $VERSION

git add .
git commit -m "release v${VERSION}"

