#!/bin/bash
# vim: set ft=sh

set -e -x

VERSION=$(cat ./version/number)
if [ -z "$VERSION" ]; then
  echo "missing version number"
  exit 20
fi

cp jfrog-artf-bosh-concourse-credentials/bosh/private.yml artifactory-bosh-release-master/config/private.yml 

cd artifactory-bosh-release-master

git config --global user.email "ci@localhost"
git config --global user.name "CI Bot"

bosh -n create release --final --with-tarball --version $VERSION

git add .
git commit -m "release v${VERSION}"
git tag -a "v${VERSION}" -m 'final release'

