#!/bin/bash
# vim: set ft=sh

set -e -x

#cannot use git clone because step does not have credentials for route-registrar
cp -R artifactory-bosh-release-master final-bosh

VERSION=$(cat ./version/version)
if [ -z "$VERSION" ]; then
  echo "missing version number"
  exit 20
fi

ls final-bosh

ls final-bosh/config

cp jfrog-artf-bosh-concourse-credentials/bosh/private.yml ./final-bosh/config/

cd final-bosh

git config --global user.email "ci@localhost"
git config --global user.name "CI Bot"

bosh -n create release --final --with-tarball --version $VERSION

git add .
git commit -m "release v${VERSION}"

