#!/bin/bash
# vim: set ft=sh

set -e -x

cd artifactory-bosh-release-master

bundle install --path vendor/bundle

RELEASE_VERSION=$(cat ./version/number)
PRODUCT_VERSION=$(cat ./product-version/number)

bundle exec voxtur ../final_bosh_release/artifactory-bosh-release-${RELEASE_VERSION}.tgz ../artifactory-pivotal $BOSH_RELEASE_BUCKET
bundle exec voxtur_utgafa ../artifactory-pivotal $PRODUCT_VERSION

git config --global user.email "ci@localhost"
git config --global user.name "CI Bot"

git add metadata_parts/binaries.yml
git commit -m "auto-update release ${RELEASE_VERSION} in product metadata bearing version ${PRODUCT_VERSION}"
